//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_Orders { get; set; }
        public string NameOrder { get; set; }
        public decimal DesiredPrice { get; set; }
        public Nullable<int> Freelancer_ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> Moderator_ID { get; set; }
        public int Service_ID { get; set; }
        public int StatusService_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Freelancer Freelancer { get; set; }
        public virtual Moderator Moderator { get; set; }
        public virtual ServiceTable ServiceTable { get; set; }
        public virtual StatusService StatusService { get; set; }
    }
}
